### ISSUE TITLE
add ability to select which buffs (including which level and extra stats due to INT scaling) are added

### ISSUE THREAD

**Issue by solakram** [Frostiae/Flyffulator#60]
currenltly its only possible to add all RM buffs or none

**Comment by Frostiae** [comment]
![image](https://user-images.githubusercontent.com/52875912/175183180-f6637c19-94a5-4829-ab42-5d21ce64abba.png)

You can already disable individual buffs in the buff module. You can also edit the amount of INT the RM giving the buffs has. Editing levels could be a good feature indeed

**Comment by solakram** [comment]
ah very nice didnt notice that. closing it and a new issue could be opened if selecting the level of the buff is significant enough.
